# Generated by Django 4.2.1 on 2024-09-19 16:59

from django.db import migrations, models
import utilities.path


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='statistics',
            field=models.ImageField(blank=True, null=True, upload_to=utilities.path.profile_colors_path),
        ),
    ]
