# Generated by Django 4.2.1 on 2024-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepost',
            name='palette',
            field=models.CharField(blank=True, null=True),
        ),
    ]
