# Generated by Django 4.2.1 on 2024-09-13 11:39

from django.db import migrations, models
import utilities.path


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepost',
            name='file',
            field=models.FileField(upload_to=utilities.path.profile_post_path),
        ),
    ]
