# Generated by Django 4.2.1 on 2024-09-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial'),
        ('user_content', '0002_alter_profilepost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
