# Generated by Django 4.2.1 on 2024-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_content', '0003_alter_profilepost_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepost',
            name='audio_end',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profilepost',
            name='audio_start',
            field=models.FloatField(default=0),
        ),
    ]
