# Generated by Django 4.2.1 on 2024-09-16 01:40

from django.db import migrations, models
import django.db.models.deletion
import utilities.path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('audio', models.FileField(blank=True, null=True, upload_to=utilities.path.audio_path)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=utilities.path.audio_cover_path)),
                ('enable', models.BooleanField(default=True)),
                ('duration', models.FloatField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
