# Generated by Django 4.2.1 on 2024-09-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='times',
            field=models.CharField(blank=True, null=True),
        ),
    ]
