# Generated by Django 4.2.1 on 2024-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_song_audio_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
